OGR: OGRUnionLayer Class Reference
OGRUnionLayer Class Reference
Generated for GDAL by 1.7.1.