OGR: OGRCoordinateTransformation Class Reference
OGRCoordinateTransformation Class Reference
#include <ogr_spatialref.h>
Generated for GDAL by 1.7.1.