OGR: OGRDataSource Class Reference
OGRDataSource Class Reference
#include <ogrsf_frmts.h>
Generated for GDAL by 1.7.1.