OGR: OGRWarpedLayer Class Reference
OGRWarpedLayer Class Reference
Generated for GDAL by 1.7.1.