OGR: CPLODBCSession Class Reference
CPLODBCSession Class Reference
#include <cpl_odbc.h>
Public Member Functions
int EstablishSession (const char *pszDSN, const char *pszUserid, const char *pszPassword)
const char * GetLastError ()
Detailed Description
A class representing an ODBC database session.
Includes error collection services.
Member Function Documentation
int CPLODBCSession::EstablishSession (const char * pszDSN, const char * pszUserid, const char * pszPassword)
Connect to database and logon.
Parameters:
pszDSN The name of the DSN being used to connect. This is not optional.
pszUserid the userid to logon as, may be NULL if not not required, or provided by the DSN.
pszPassword the password to logon with. May be NULL if not required or provided by the DSN.
Returns:
TRUE on success or FALSE on failure. Call GetLastError() to get details on failure.
References GetLastError().
const char * CPLODBCSession::GetLastError ()
Returns the last ODBC error message.
Returns:
pointer to an internal buffer with the error message in it. Do not free or alter. Will be an empty (but not NULL) string if there is no pending error info.
Referenced by EstablishSession(), and CPLODBCStatement::Fetch().
The documentation for this class was generated from the following files:
cpl_odbc.h
cpl_odbc.cpp
Generated for GDAL by 1.7.1.