OGR: OGRMutexedDataSource Class Reference
OGRMutexedDataSource Class Reference
#include <ogrmutexeddatasource.h>
Generated for GDAL by 1.7.1.