OGR: OGRGenSQLResultsLayer Class Reference
OGRGenSQLResultsLayer Class Reference
Generated for GDAL by 1.7.1.