OGR: OGRProxiedLayer Class Reference
OGRProxiedLayer Class Reference
Generated for GDAL by 1.7.1.