OGR: OGRLayerDecorator Class Reference
OGRLayerDecorator Class Reference
Generated for GDAL by 1.7.1.