OGR: OGRGeometryCollection Class Reference
OGRGeometryCollection Class Reference
#include <ogr_geometry.h>
Generated for GDAL by 1.7.1.