OGR: OGRGeomFieldDefn Class Reference
OGRGeomFieldDefn Class Reference
#include <ogr_feature.h>
Generated for GDAL by 1.7.1.