OGR: ogr_spatialref.h File Reference
ogr_spatialref.h File Reference
#include "ogr_srs_api.h"
Classes
class OGR_SRSNode
class OGRSpatialReference
class OGRCoordinateTransformation
Functions
OGRCoordinateTransformation * OGRCreateCoordinateTransformation (OGRSpatialReference *poSource, OGRSpatialReference *poTarget)
Detailed Description
Coordinate systems services.
Function Documentation
OGRCoordinateTransformation* OGRCreateCoordinateTransformation (OGRSpatialReference * poSource, OGRSpatialReference * poTarget)
Create transformation object.
This is the same as the C function OCTNewCoordinateTransformation().
Input spatial reference system objects are assigned by copy (calling clone() method) and no ownership transfer occurs.
The delete operator, or OCTDestroyCoordinateTransformation() should be used to destroy transformation objects.
The PROJ.4 library must be available at run-time.
Parameters:
poSource source spatial reference system.
poTarget target spatial reference system.
Returns:
NULL on failure or a ready to use transformation object.
References OGRCreateCoordinateTransformation().
Referenced by OCTNewCoordinateTransformation(), OGRCreateCoordinateTransformation(), and OGRGeometry::transformTo().
Generated for GDAL by 1.7.1.