#!/bin/sh
CONFIG_LIBS="-framework GDAL"
CONFIG_DEP_LIBS=""
CONFIG_PREFIX="/Library/Frameworks/GDAL.framework/Versions/1.11"
CONFIG_CFLAGS="-I/Library/Frameworks/GDAL.framework/Versions/1.11/Headers"
CONFIG_DATA="/Library/Frameworks/GDAL.framework/Versions/1.11/Resources/gdal"
CONFIG_VERSION="1.11.0"
CONFIG_OGR_ENABLED=yes
CONFIG_FORMATS="gxf gtiff hfa aigrid aaigrid ceos ceos2 iso8211 xpm sdts raw dted mem jdem envisat elas fit vrt usgsdem l1b nitf bmp pcidsk airsar rs2 ilwis rmf leveller sgi srtmhgt idrisi gsg ingr ers jaxapalsar dimap gff cosar pds adrg coasp tsx terragen blx msgn til r northwood saga xyz hf2 kmlsuperoverlay ctg e00grid zmap ngsgeoid iris map webp wcs wms dods grib bsb openjpeg jpeg2000 netcdf hdf5 hdf4 ogdi gif jpeg gta png pcraster fits  rik ozi rasterlite mbtiles postgisraster arg"
usage()
{
	cat <<EOF
Usage: gdal-config [OPTIONS]
Options:
	[--prefix[=DIR]]
	[--libs]
	[--dep-libs]
	[--cflags]
	[--datadir]
	[--version]
	[--ogr-enabled]
	[--formats]
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

case $1 in 
  --libs)
    echo $CONFIG_LIBS
    ;;

  --dep-libs)
    echo $CONFIG_DEP_LIBS
    ;;

  --cflags)
    echo $CONFIG_CFLAGS
    ;;

  --datadir)
    echo $CONFIG_DATA
    ;;

  --prefix)
    echo $CONFIG_PREFIX
    ;;

  --version)
    echo $CONFIG_VERSION
    ;;

  --ogr-enabled)
    echo $CONFIG_OGR_ENABLED
    ;;

  --formats)
    echo $CONFIG_FORMATS
    ;;

  *)
    usage 1 1>&2
    ;;

esac
